ROCm port
3b5ee46 NVBenchRapidsCMake*:configurable ROCm-DS.cmake repo <> Thu Apr 24 20:26:42 2025 +0000 <> domcharrier <docharri@amd.com>
Make the repository from which to obtain the ROCm-DS.cmake
script configurable via the environment variable
`ROCm-DS_CMAKE_SCRIPT_REPO`.

e750bc0 bump minimum CMake version to 3.23 for rocm-ds-cmake compatibility <> Mon Apr 14 02:44:48 2025 -0700 <> Philipp Samfass <philipp.samfass@amd.com>

8cb2b22 feat(*RapidsCMake.*): ROCm-DS_CMAKE_MODULE_PATH <> Mon Apr 14 06:25:37 2025 +0000 <> domcharrier <docharri@amd.com>
Change to ROCm-DS_CMAKE_MODULE_PATH from ROCm-DS_CMAKE_FROM_MODULE_PATH
as this allows setting pointing to the ROCmDS-CMake module
files via an environment variable, which in turn allows to
inject this information easier into more complex build
processes (scikit-build).

11072be cmake/tests/*:use nvbench:: tgts via hipbench pkg <> Tue Apr 1 13:25:42 2025 +0000 <> domcharrier <docharri@amd.com>
Add option `FIND_NVBENCH` to switch between the two packages
provided by a hipbench installation.

b1da144 feat(cmake): hipbench pkg provides nvbench:: too <> Tue Apr 1 13:24:13 2025 +0000 <> domcharrier <docharri@amd.com>
find_pacakge(hipbench) now also provides access
to the `nvbench::` targets.

36ce614 cmake/tests: add test for find_package(hipbench) <> Fri Mar 28 13:41:46 2025 +0000 <> docharri@amd.com <domcharrier>

5c26c6a cmake: export a hipbench package too <> Mon Mar 31 09:04:04 2025 +0000 <> docharri@amd.com <domcharrier>

4f91ba5 feat(nvbench/CMake*.txt): add hipbench targets <> Mon Mar 31 08:55:29 2025 +0000 <> docharri@amd.com <domcharrier>
* Provide hipbench:: ALIAS targets for add_subdirectory type usage.
* Create and install hipbench INTERFACE target that is linked with
  nvbench.

5eff081 CMakeLists.txt: disable installing CPM downloads <> Fri Mar 28 16:11:06 2025 +0000 <> docharri@amd.com <domcharrier>
Add option for disabling installation of packages
downloaded by CPM. This won't affect packages that
CPM has found locally as those are not installed
in any case.

Motivation:

When creating packages, one might want to package/install
the NVBench files in isolation and not install libhipcxx
files.

759bfce feat(CMakeLists.txt): use packaging cmake module <> Fri Mar 28 11:24:49 2025 +0000 <> domcharrier <docharri@amd.com>

d394d2f + cmake/NVBenchPackaging.cmake: includes CPACK <> Fri Mar 28 11:24:18 2025 +0000 <> domcharrier <docharri@amd.com>

935ee1f hotfix(NVBenchDependencies.cmake): use fmt version from ROCm-DS-cmake <> Wed Mar 26 02:49:13 2025 -0700 <> Philipp Samfass <philipp.samfass@amd.com>
Details:

fmt 9.1.0 fails to compile with more recent gcc versions (observed with
GCC 13.3.0).
We now let rocm-ds-cmake pick the fmt version which in this case
happens to be 10.* and which no longer suffers from the previously
observed compiler error:

```
/home/sphilipp/hipBench/build/_deps/fmt-src/include/fmt/core.h:1735:15: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
1735 |   const auto& arg = arg_mapper<Context>().map(FMT_FORWARD(val));
      |               ^~~
/home/sphilipp/hipBench/build/_deps/fmt-src/include/fmt/core.h:1735:46: note: the temporary was destroyed at the end of the full expression 'fmt::v9::detail::arg_mapper<fmt::v9::basic_format_context<fmt::v9::appender, char> >().fmt::v9::detail::arg_mapper<fmt::v9::basic_format_context<fmt::v9::appender, char> >::map<std::vector<std::__cxx11::basic_string<char> >&>((* & val))'
1735 |   const auto& arg = arg_mapper<Context>().map(FMT_FORWARD(val));
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

bd776c5 feat: +option to find ROCmDS-CMake on module path <> Tue Mar 18 18:20:23 2025 +0000 <> domcharrier <docharri@amd.com>
Adds an option ROCm-DS_CMAKE_FROM_MODULE_PATH [default=OFF]
that disables fetching of ROCm-DS CMake script and repo
assuming that ROCm-DS CMake modules can be found via the
CMAKE_MODULE_PATH.

38836c6 doc: add disclaimer <> Fri Dec 6 17:46:22 2024 +0100 <> Philipp Samfass <philipp.samfass@amd.com>

4a2e88e add .gitignore <> Mon Oct 28 19:36:25 2024 +0000 <> charlifu <charlifu@amd.com>
Signed-off-by: charlifu <charlifu@amd.com>

a5e1311 fix(type_axis.cxx): explicitly cast to size_t to avoid sign conversion warning <> Tue Oct 29 08:58:25 2024 -0700 <> Philipp Samfass <philipp.samfass@amd.com>

1aa00cc + versions.json: empty, allows updating via CI <> Thu Sep 19 08:32:36 2024 +0000 <> domcharrier <docharri@amd.com>
* Allows to control dependencies from CI process.

NOTE ("first to record wins"):

"If a project is listed in multiple override files, the first file values will be used,
and all later calls for that packaged will be ignored. This "first to record, wins"
approach is used to match FetchContent, and allows parent projects to override child
projects."

73d4e9c sync: use public rapids-cmake <> Thu Sep 19 09:17:57 2024 +0000 <> domcharrier <docharri@amd.com>
Synchronize branch with public hipBench repo.

a684069 doc(README.md): fix formatting of example output in README <> Fri Sep 6 01:48:14 2024 -0700 <> Philipp Samfass <philipp.samfass@amd.com>

3dde7a6 fix(testing/cm*/test*/CMakeLists.*):all tests pass <> Thu Sep 5 19:30:18 2024 +0000 <> domcharrier <docharri@amd.com>
Reintroduce code that was removed during hipification process.
Now all tests pass (assuming CMAKE_PREFIX_PATH contains the ROCm path).

c9594d4 fix(testing/cmake/CMakeLists.txt): + libhipcxx_DIR <> Thu Sep 5 18:51:11 2024 +0000 <> domcharrier <docharri@amd.com>
In addition to

```
-D "NVBench_DIR=${tmp_install_prefix}/lib/cmake/nvbench/"
```

we add

```
-D "libhipcxx_DIR=${tmp_install_prefix}/lib/rapids/cmake/libhipcxx/"
```

This fixes the last failing test `nvbench.test.cmake.test_export.install_tree` to 50 %.

Verbose test output:

    ```cmake
    36: Running test command: "/opt/conda/envs/cudf_dev/bin/ctest" "--output-on-failure"
    36: Test command failed: /opt/conda/envs/cudf_dev/bin/ctest
    36: Test project /home/mohammad/docharri/hipdf/DEPS/hipbench/build/testing/cmake/test_export/install_tree
    36:     Start 1: test_bench
    36: 1/2 Test #1: test_bench .......................   Passed    1.65 sec
    36:     Start 2: nvbench_ctl
    36: 2/2 Test #2: nvbench_ctl ......................***Failed    0.00 sec
    36: /home/mohammad/docharri/hipdf/DEPS/hipbench/build/testing/cmake/test_nvbench_install/bin/nvbench-ctl: error while loading shared libraries: libnvbench.so: cannot open shared object file: No such file or directory
    ```

The respective code is in:

`testing/cmake/test_export/CMakeLists.txt`

This file contains a section with the comment "# Setup LD_LIBRARY_PATH for testing".
Very likely this has something to do with the remaining issue.

650008b fix(**Libhipcxx.cmake): use correct export sets <> Thu Sep 5 18:35:26 2024 +0000 <> domcharrier <docharri@amd.com>
Use same sets as other targets: `nvbench-targets`.

This fixes test `nvbench.test.cmake.test_export.build_tree`
but not the last failing test `nvbench.test.cmake.test_export.install_tree`.

c82ec85 fix(**CMakeLists.txt): HIP lang + CUDA=HIP archs <> Thu Sep 5 18:33:00 2024 +0000 <> domcharrier <docharri@amd.com>
Use HIP lang instead of CUDA.
Allow CMAKE_HIP_ARCHITECTURES and
CMAKE_CUDA_ARCHITECTURES for specifying
AMD GPUs.

301ca37 update ReadMe file <> Tue Jun 4 16:01:27 2024 +0000 <> monoatamd <mnorouzi@amd.com>

336f81e retain nvidia copyright line <> Wed May 8 12:08:04 2024 +0000 <> monoatamd <mnorouzi@amd.com>

44e3b73 update licenses <> Wed May 8 12:01:08 2024 +0000 <> monoatamd <mnorouzi@amd.com>

b5e7b3d update linceses <> Tue May 7 16:51:29 2024 +0000 <> monoatamd <mnorouzi@amd.com>

42941e4 update licnese <> Tue May 7 16:19:23 2024 +0000 <> monoatamd <mnorouzi@amd.com>

8d8a210 Remove CI related files. Need to port them later. <> Tue May 7 15:49:14 2024 +0000 <> monoatamd <mnorouzi@amd.com>

28b7743 Remove a WAR: <> Tue May 7 15:46:06 2024 +0000 <> monoatamd <mnorouzi@amd.com>
The WAR worked some time ago (https://<redacted>hipBench/commit/6068389724a4bf427612c27ebbdd8b8ff23284ae) and now caues an error: hipErrorInvalidDevice: invalid device ordinal. Also, enable some parts of the code which was disabled before in the same commit.

d66ea34 fix file extensions <> Tue May 7 15:16:41 2024 +0000 <> monoatamd <mnorouzi@amd.com>

cc297cf rename file extensions to hip from cu.cpp <> Tue May 7 14:08:24 2024 +0000 <> monoatamd <mnorouzi@amd.com>

34a5155 Code cleanup: remove unused (CUPTI AND NVML) files, delete MSVC related snippets in build system. <> Tue May 7 12:49:50 2024 +0000 <> monoatamd <mnorouzi@amd.com>

a57c0cf docfix(README.md): add required settings for CMAKE_PREFIX_PATH <> Fri Sep 6 03:05:43 2024 -0700 <> Philipp Samfass <philipp.samfass@amd.com>

b13cf2f doc(README.md): revise README to include necessary information for HIP port <> Fri Sep 6 01:24:18 2024 -0700 <> Philipp Samfass <philipp.samfass@amd.com>

4e391e7 fix build of noisy bench <> Fri Nov 10 01:45:00 2023 -0800 <> Philipp Samfass <philipp.samfass@amd.com>

3d839b3 let CMake decide which compiler to use for CXX files <> Fri Nov 10 01:07:56 2023 -0800 <> Philipp Samfass <philipp.samfass@amd.com>

487fa8d WIP: allow compiling host code without hipclang <> Fri Nov 10 00:57:18 2023 -0800 <> Philipp Samfass <philipp.samfass@amd.com>

42b8b99 bugfix: fixed markdown output for HIP + fixed a few compiler warnings <> Wed Jun 14 13:46:32 2023 +0000 <> Philipp Samfass <philipp.samfass@amd.com>

21273d3 fix: delete move assignment as default assignment cannot be generated by hipcc <> Tue Jun 13 12:17:51 2023 +0000 <> Philipp Samfass <philipp.samfass@amd.com>

7dfa4e5 fix streams in state_generator <> Thu Jun 1 13:33:06 2023 +0200 <> Philipp Samfass <philipp.samfass@amd.com>
We found that the streams are not necessarily created on the device
on which they will be used. Therefore, we set the correct device
with device->set_active before creating the state (which in turn creates the
stream). This also seems to fix timeout warnings we have seen in some benchmarks.

00eecda feat: Fix error about default move operator deleted <> Wed May 31 10:21:46 2023 +0000 <> monoatamd <mnorouzi@amd.com>

5857d5b feat: Build tests/examples <> Tue May 30 08:07:35 2023 +0000 <> monoatamd <mnorouzi@amd.com>

c0237aa feat: Adapt cmake files <> Tue May 30 07:11:33 2023 +0000 <> monoatamd <mnorouzi@amd.com>

Co-authored-by: psamfass <psamfass@amd.com>
Co-authored-by: monoatamd <mnorouzi@amd.com>
Co-authored-by: domcharrier <docharri@amd.com>
Co-authored-by: reger-men <adil.lashab@amd.com>
Co-authored-by: dkbhaskaran <dineshkumarb@gmail.com>
Co-authored-by: charlifu <charlifu@amd.com>
Co-authored-by: obersteiner <moberste@amd.com>